language: python

sudo: false

python:
  - "3.4.3"
  - "3.5.1"

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -c "CREATE ROLE odm WITH PASSWORD 'odmtest';"
  - psql -U postgres -c "ALTER USER odm CREATEDB;"
  - psql -U postgres -c "ALTER USER odm LOGIN;"
  - psql -U postgres -c "CREATE DATABASE odmtests;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE odmtests to odm;"

script:
  - flake8
  - rm -rf odm
  - python -m runtests --coverage

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.1' ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
