language: python

python:
  - 3.5.2
  - 3.6-dev

install:
  - pip install -r requirements-dev.txt

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -f tests/db.sql

script:
  - flake8
  - python setup.py test --coverage -q

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.2' ]]; then python setup.py test --coveralls; fi

notifications:
  email: false
