language: python

python:
  - "3.4"

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "CREATE ROLE odm WITH PASSWORD 'odmtest';"
  - psql -U postgres -c "ALTER USER lux CREATEDB;"
  - psql -U postgres -c "ALTER USER lux LOGIN;"
  - psql -U postgres -c "CREATE DATABASE odmtests;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE odmtests to odm;"

script:
  - pep8
  - python -m runtests --coverage
  - python -m runtests --coveralls

notifications:
  email: false

branches:
  only:
    - master