language: python

sudo: false

python:
  - "3.4"

before_install:
  - echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - apt-get install rethinkdb
  - apt-get install -qq libhdf5-serial-dev liblzo2-dev libbz2-dev python3-numpy
  - pip install cython numpy numexpr

install:
  - pip install -r requirements_dev.txt
  - python setup.py install

before_script:
  - rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 5

script:
  - pep8
  - rm -rf odm
  - rm -rf pulsar_odm.egg-info
  - python -m runtests --coverage
  - python -m runtests --coveralls

after_script:
  - killall rethinkdb

notifications:
  email: false

branches:
  only:
    - master