language: python

sudo: false

python:
  - "3.4"

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  - psql -U postgres -c "CREATE ROLE odm WITH PASSWORD 'odmtest';"
  - psql -U postgres -c "ALTER USER odm CREATEDB;"
  - psql -U postgres -c "ALTER USER odm LOGIN;"
  - psql -U postgres -c "CREATE DATABASE odmtests;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE odmtests to odm;"

script:
  - flake8
  - sudo rm -rf odm
  - python -m runtests --coverage
  - python -m runtests --coveralls

notifications:
  email: false

branches:
  only:
    - master
    - dev
