language: python

python:
  - "3.4"

before_install:
  - echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb

install:
  - pip install -r requirements_dev.txt
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 10

script:
  - pep8 odm tests
  - sudo rm -rf odm
  - python -m runtests --coverage

after_script:
  - killall rethinkdb

notifications:
  email: false

branches:
  only:
    - master